### PR TITLE
Launcher does some error checking

### PR DESCRIPTION
**Pull request by rickardnorlander**

### CODE REVIEW

**Comment by SpenserJ** [comment]
#### :ballot_box_with_check: Voting procedure reminder:
To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

*NOTE: the PR will be closed if any new commits are added after:* de51bc20457cef549320c0cf6115f8bd365d363a

**Comment by SpenserJ** [comment]
:-1:

**Comment by SpenserJ** [comment]
For clarification, I didn't thumb that down, the bot did on my behalf.

**Comment by rickardnorlander** [comment]
Yeah, I got that :)

**Comment by SpenserJ** [comment]
#### :ballot_box_with_check: Voting procedure reminder:

To cast a vote, post a comment containing `:+1:` (:+1:), or `:-1:` (:-1:).
Remember, you **must :star:star this repo for your vote to count.**

All comments within this discussion are searched for votes, regardless of the time of posting.
You can cast as many votes as you want, but only the last one will be counted.
(You may consider editing your comment instead of adding a new one.)
Comments containing both up- and down-votes are disregarded.
PR authors automatically count as a :+1: vote.

A decision will be made after this PR has been open for **15** minutes (plus/minus **10** percent, to avoid people timing their votes), and at least **8** votes have been made.
A supermajority of **65%** is required for the vote to pass.

_NOTE: the PR will be closed if any new commits are added after:_ de51bc20457cef549320c0cf6115f8bd365d363a

**Comment by SpenserJ** [comment]
:-1:

**Pull request merged**
